### ISSUE TITLE
Reduce dependency on built in template engine

### ISSUE THREAD

**Issue by timfpark** [fabriq-cloud/fabriq#65]
`Gitops` processor current templates out templates using handlebars, but there is a simpler and lower maintenance solution in the existing ecosystem that also fits in better with the `flux` implementation by just using `helm`.

Templates in this approach are just `helm` templates.  When we create a template, we pass it three items:

`id`, `repo`, `ref`, and `path`

These would be used, in a GitOps/flux backend, to produce a global `HelmRepository` output (deployed on every cluster once):

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: {{id}}
spec:
  url: {{repo}}
  interval: 10m
```

and a per host assignment release:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: {{template:path}}
      version: {{template:ref}}
      sourceRef:
        kind: HelmRepository
        name: {{template:id}}
  values:
     config1: value1
     config2: value2
     ... 
```

Unresolved Challenges:

* config does not map cleanly - some `values` definitions in templates are very complex (see `fluentbit` for example)
